context: gitlab-deploy

environments:
  development:
  production:

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: coreos
  url: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

releases:
- name: torproxy
  namespace: secureworks
  chart: ./charts/torproxy/
  set:
    - name: image
      value: {{ requiredEnv "IMAGE" }}:{{ requiredEnv "RELEASE_TAG" }}
    - name: releaseHash
      value: {{ requiredEnv "CI_COMMIT_SHA" }}
  values:
    - ./charts/torproxy/values.yaml
    - ./deployments/{{  .Environment.Name  }}.yaml
    - resources:
        limits:
          cpu: 512m
          memory: 512Mi
          ephemeral-storage: 1Gi
        requests:
          cpu: 256m
          memory: 128Mi
          ephemeral-storage: 120Mi
  wait: true
