apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "detector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service_app: {{ .Values.torproxy.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.dnmsearcher.image }}:{{ .Values.dnmsearcher.tag }}
        {{- if .Values.useLocalImage }}
        imagePullPolicy: IfNotPresent
        {{- end }}
      - name: {{ .Values.torproxy.name }}
        image: {{ .Values.torproxy.image }}
        ports:
        - containerPort: {{ .Values.torproxy.port }}
        {{- if .Values.useLocalImage }}
        imagePullPolicy: IfNotPresent
        {{- end }}
