{{- if .Values.ingress.enabled -}}
{{- $fullName := include "detector.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "detector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "detector.fullname" . }}
          servicePort: {{ .Values.service.port }}
{{- end }}
