apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.torproxy.name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "detector.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    service_app: {{ .Values.torproxy.name }}
  type: {{ .Values.torproxy.serviceType }}
  ports:
    - protocol: TCP
      port: {{ .Values.torproxy.port }}
